version: "3"

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=news
      - POSTGRES_PASSWORD=news
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/news
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: